---
- name: Cloning the "{{ repo_name }}" repo
  git:
    repo: "{{ source_url }}"
    dest: '{{ git_dir }}/{{ repo_name }}'
    version: master
    #clone: yes
    update: no

- name: fetch specific branches
  ansible.builtin.shell: |
    git --git-dir={{ git_dir }}/{{ repo_name }}/.git fetch origin
    git --git-dir={{ git_dir }}/{{ repo_name }}/.git show-ref refs/heads/{{ item }}
    if [ $? -eq 0 ]
    then
        #echo "branch {{ item }} exists"
        git --git-dir={{ git_dir }}/{{ repo_name }}/.git checkout {{ item }}
        git --git-dir={{ git_dir }}/{{ repo_name }}/.git pull
    else
        #echo "branch {{ item }} not exists $?" 
        git --git-dir={{ git_dir }}/{{ repo_name }}/.git checkout --track origin/{{ item }}
    fi
  with_items: "{{ branches }}"
- name: fetch remote tags
  ansible.builtin.shell: git fetch --tags --force --progress -- {{ source_url }} +refs/heads/*:refs/remotes/origin/*

- name: Add alternate remote
  ini_file:
    dest: '{{ git_dir }}/{{ repo_name }}/.git/config'
    section: 'remote "mirrored"'
    option: url
    value: "{{ dest_url }}"
  tags: configuration
 
- name: Push the repo to alternate remote
  ansible.builtin.shell: 'git --git-dir={{ git_dir }}/{{ repo_name }}/.git push mirrored {{ item }}'
  with_items: "{{ branches }}"

- name: get latest 3 tags
  ansible.builtin.shell: 
    cmd:  'git for-each-ref refs/tags/* --sort=-authordate  --format="%(refname)"" --count=3|awk -F/ "{print $3;}"'
    chdir: "{{ git_dir }}"
  register: tags
  
- name: push tag {{ item }}.
  ansible.builtin.shell: 'git --git-dir={{ git_dir }}/{{ repo_name }}/.git push mirrored {{ item }}'
  with_items: "{{ tags.stdout_lines }}"

